[package]
name = "crossbow-manga-lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "crossbow_manga_lib"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16", features = ["extension-module"] }
numpy = "0.16"
